### ISSUE TITLE
Could you please add a license

### ISSUE THREAD

**Issue by AP-Frank** [ShubhankarKulkarni/MIL-STD-1553-Simulator#1]
Hello,

when going through your code I noticed that it currently is not placed under a license. I don't know if this is a deliberate decision, but technically it prevents other people from working with your code (As explained [here](https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it)).

Would you mind adding a license?

Thank you for considering

**Comment by ShubhankarKulkarni** [comment]
Thanks for pointing that out, Frank. I added the GPL v2 License to the repository.
